DELETE http://localhost:3001/api/persons/1 HTTP/1.1
###
GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/688ed4133267d7791c99a280
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Sean",
    "number": "86-520123"
}
###
PUT http://localhost:3001/api/persons/6890888c58c90fdf42f4d5d9 HTTP/1.1
content-type: application/json

{
    "name": "Yi",
    "number": "321"
}
