DELETE http://localhost:3001/api/persons/1 HTTP/1.1
###
GET http://localhost:3001/api/persons/
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Hellas",
    "number": "123",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
